---
title: "Coronavirus"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
 #    vertical_layout: scroll
  #  vertical_layout: fill
---


```{r label = Sindh, include = FALSE}
knitr::read_chunk("03Sindh.R")
```


```{r label = SindhPackages, include = FALSE}
```

```{r label = SindhParameters}
```


```{r label = SindhCoronaData}
```

Sindh
======================================================================

Row
----------------------------------------------------------------------
  
### Confirmed {.value-box}
```{r label = SindhConfirmed}
```

### Active {.value-box}
```{r label = SindhActive}
```

### Recovered {.value-box}
```{r label = SindhRecovered}
```


### Death {.value-box}
```{r label = SindhDeaths}
```


Row
----------------------------------------------------------------------

### Cumulative Number of Confirmed Cases
```{r label = SindhConfirmedPlot1}
```

### Cumulative Number of Active Cases
```{r label = SindhActivePlot1}
```


### Number of New Cases
```{r label = SindhNewPlot1}
```


Sindh
======================================================================

Row
----------------------------------------------------------------------
  
### Confirmed {.value-box}
```{r label = SindhConfirmed}
```

### Active {.value-box}
```{r label = SindhActive}
```

### Recovered {.value-box}
```{r label = SindhRecovered}
```


### Death {.value-box}
```{r label = SindhDeaths}
```


Row
----------------------------------------------------------------------

### Number of Recovered Cases
```{r label = SindhRecoveredPlot1}
```


### Number of Deaths
```{r label = SindhDeathsPlot1}
```

### Data for COVID-19
```{r label = SindhCoronaData1}
```

