---
title: "Coronavirus"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
 #    vertical_layout: scroll
  #  vertical_layout: fill
---




Pakistan
======================================================================

Row
----------------------------------------------------------------------
  
### Confirmed {.value-box}
```{r label = PakConfirmed}
```

### Active {.value-box}
```{r label = PakActive}
```

### Recovered {.value-box}
```{r label = PakRecovered}
```


### Death {.value-box}
```{r label = PakDeaths}
```


Row
----------------------------------------------------------------------

### Number of Recovered Cases
```{r label = PakRecoveredPlot1}
```


### Number of Deaths
```{r label = PakDeathsPlot1}
```

### Data for COVID-19
```{r label = PakCoronaData1}
```


Punjab
======================================================================

Row
----------------------------------------------------------------------
  
### Confirmed {.value-box}
```{r label = PakConfirmed}
```

### Active {.value-box}
```{r label = PakActive}
```

### Recovered {.value-box}
```{r label = PakRecovered}
```


### Death {.value-box}
```{r label = PakDeaths}
```


Row
----------------------------------------------------------------------


Sindh
======================================================================

Row
----------------------------------------------------------------------
  
### Confirmed {.value-box}

```{r label = PakConfirmed}
```

### Active {.value-box}

```{r label = PakActive}
```

### Recovered {.value-box}

```{r label = PakRecovered}
```


### Death {.value-box}

```{r label = PakDeaths}
```


Row
----------------------------------------------------------------------


KPK
======================================================================

Row
----------------------------------------------------------------------
  
### Confirmed {.value-box}

```{r label = PakConfirmed}
```

### Active {.value-box}

```{r label = PakActive}
```

### Recovered {.value-box}

```{r label = PakRecovered}
```


### Death {.value-box}

```{r label = PakDeaths}
```


Row
----------------------------------------------------------------------



Balochistan
======================================================================

Row
----------------------------------------------------------------------
  
### Confirmed {.value-box}

```{r label = PakConfirmed}
```

### Active {.value-box}

```{r label = PakActive}
```

### Recovered {.value-box}

```{r label = PakRecovered}
```


### Death {.value-box}

```{r label = PakDeaths}
```


Row
----------------------------------------------------------------------


ICT
======================================================================

Row
----------------------------------------------------------------------
  
### Confirmed {.value-box}

```{r label = PakConfirmed}
```

### Active {.value-box}

```{r label = PakActive}
```

### Recovered {.value-box}

```{r label = PakRecovered}
```


### Death {.value-box}

```{r label = PakDeaths}
```


Row
----------------------------------------------------------------------



Gilgit Baltistan
======================================================================

Row
----------------------------------------------------------------------
  
### Confirmed {.value-box}

```{r label = PakConfirmed}
```

### Active {.value-box}

```{r label = PakActive}
```

### Recovered {.value-box}

```{r label = PakRecovered}
```


### Death {.value-box}

```{r label = PakDeaths}
```


Row
----------------------------------------------------------------------


AJK
======================================================================

Row
----------------------------------------------------------------------
  
### Confirmed {.value-box}

```{r label = PakConfirmed}
```

### Active {.value-box}

```{r label = PakActive}
```

### Recovered {.value-box}

```{r label = PakRecovered}
```


### Death {.value-box}

```{r label = PakDeaths}
```


Row
----------------------------------------------------------------------

